pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/filipacardoso/devops-23-24-JPE-1231827.git'
            }
        }

        stage('Assemble') {
            steps {
                echo 'Assembling...'
                dir('CA2/part1') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean assemble'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Testing...'
                dir('CA2/part1') {
                    sh './gradlew test'
                }
            }
            post {
                always {
                    junit '**/build/test-results/**/*.xml'
                }
            }
        }

        stage('Archive') {


            steps {
                echo 'Archiving...'
                dir('CA2/part1') {
                    archiveArtifacts artifacts: 'build/libs/*.jar'
                }
            }
        }
    }
}
